# Generated by Django 3.1.1 on 2020-10-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('isactive', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('key', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('isactive', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workprofile', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('isactive', models.BooleanField(default=1)),
            ],
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(fields=('workprofile',), name='guardian_work_uk_workprofile'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.UniqueConstraint(fields=('qualification',), name='guardian_qualification_uk_qualification'),
        ),
    ]
